- id: xmlstarlet-format
  name: Format XML using xmlstarlet
  entry: bash -c "echo $PATH"
  language: system
  files: \.xml$

- id: sort-xml
  name: Sort XML attributes using XSLT
  entry: sort-xml.sh
  language: system
  files: \.xml$