- id: sort-xml
  name: Sort XML attributes using XSLT
  entry: sort-xml.sh
  language: script
  files: \.xml$
- id: xmlstarlet-format
  name: Format XML using xmlstarlet
  entry: xmlstarlet-format.sh
  language: script
  files: \.xml$
- id: make_odoo_robot_tests_githubworkflow
  name: Creates a github workflow for unit and robotests
  entry: make-odoo-robot-tests-githubworkflow
  language: python
  pass_filenames: false
  always_run: true
  args: []
