- id: show-info
  name: Format XML using xmlstarlet
  entry: |
    print("HALLO")
  language: python
  files: \.xml$
- id: xmlstarlet-format
  name: Format XML using xmlstarlet
  entry: bash xmlscarlet-format.sh
  language: system
  files: \.xml$

- id: sort-xml
  name: Sort XML attributes using XSLT
  entry: bash sort-xml.sh
  language: system
  files: \.xml$